name: Deploy on ghpages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git User Info
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Deploy!
        run: yarn deploy
